
package com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CUX_CAR_MANAGE_SYS_PKG_Service", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", wsdlLocation = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/?wsdl")
public class CUXCARMANAGESYSPKGService
    extends Service
{

    private final static URL CUXCARMANAGESYSPKGSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUXCARMANAGESYSPKGSERVICE_EXCEPTION;
    private final static QName CUXCARMANAGESYSPKGSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", "CUX_CAR_MANAGE_SYS_PKG_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUXCARMANAGESYSPKGSERVICE_WSDL_LOCATION = url;
        CUXCARMANAGESYSPKGSERVICE_EXCEPTION = e;
    }

    public CUXCARMANAGESYSPKGService() {
        super(__getWsdlLocation(), CUXCARMANAGESYSPKGSERVICE_QNAME);
    }

    public CUXCARMANAGESYSPKGService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUXCARMANAGESYSPKGSERVICE_QNAME, features);
    }

    public CUXCARMANAGESYSPKGService(URL wsdlLocation) {
        super(wsdlLocation, CUXCARMANAGESYSPKGSERVICE_QNAME);
    }

    public CUXCARMANAGESYSPKGService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUXCARMANAGESYSPKGSERVICE_QNAME, features);
    }

    public CUXCARMANAGESYSPKGService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CUXCARMANAGESYSPKGService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CUXCARMANAGESYSPKGPortType
     */
    @WebEndpoint(name = "CUX_CAR_MANAGE_SYS_PKG_Port")
    public CUXCARMANAGESYSPKGPortType getCUXCARMANAGESYSPKGPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", "CUX_CAR_MANAGE_SYS_PKG_Port"), CUXCARMANAGESYSPKGPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CUXCARMANAGESYSPKGPortType
     */
    @WebEndpoint(name = "CUX_CAR_MANAGE_SYS_PKG_Port")
    public CUXCARMANAGESYSPKGPortType getCUXCARMANAGESYSPKGPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", "CUX_CAR_MANAGE_SYS_PKG_Port"), CUXCARMANAGESYSPKGPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUXCARMANAGESYSPKGSERVICE_EXCEPTION!= null) {
            throw CUXCARMANAGESYSPKGSERVICE_EXCEPTION;
        }
        return CUXCARMANAGESYSPKGSERVICE_WSDL_LOCATION;
    }

}
