
package com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CUX_CAR_MANAGE_SYS_PKG_PortType", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.ObjectFactory.class,
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.del_car_vendors_list.ObjectFactory.class,
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_batch_list.ObjectFactory.class,
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_order_list.ObjectFactory.class,
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_vendors_list.ObjectFactory.class,
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_batch_list.ObjectFactory.class,
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_vendors_list.ObjectFactory.class,
    com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.update_car_vendors_list.ObjectFactory.class
})
public interface CUXCARMANAGESYSPKGPortType {


    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.del_car_vendors_list.OutputParameters
     */
    @WebMethod(operationName = "DEL_CAR_VENDORS_LIST", action = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/del_car_vendors_list/", partName = "body")
    public com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.del_car_vendors_list.OutputParameters delCARVENDORSLIST(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/del_car_vendors_list/", partName = "body")
        com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.del_car_vendors_list.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_batch_list.OutputParameters
     */
    @WebMethod(operationName = "GET_CAR_BATCH_LIST", action = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/get_car_batch_list/", partName = "body")
    public com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_batch_list.OutputParameters getCARBATCHLIST(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/get_car_batch_list/", partName = "body")
        com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_batch_list.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_order_list.OutputParameters
     */
    @WebMethod(operationName = "GET_CAR_ORDER_LIST", action = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/get_car_order_list/", partName = "body")
    public com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_order_list.OutputParameters getCARORDERLIST(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/get_car_order_list/", partName = "body")
        com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_order_list.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_vendors_list.OutputParameters
     */
    @WebMethod(operationName = "GET_CAR_VENDORS_LIST", action = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/get_car_vendors_list/", partName = "body")
    public com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_vendors_list.OutputParameters getCARVENDORSLIST(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/get_car_vendors_list/", partName = "body")
        com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.get_car_vendors_list.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_batch_list.OutputParameters
     */
    @WebMethod(operationName = "INSERT_CAR_BATCH_LIST", action = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/insert_car_batch_list/", partName = "body")
    public com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_batch_list.OutputParameters insertCARBATCHLIST(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/insert_car_batch_list/", partName = "body")
        com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_batch_list.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_vendors_list.OutputParameters
     */
    @WebMethod(operationName = "INSERT_CAR_VENDORS_LIST", action = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/insert_car_vendors_list/", partName = "body")
    public com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_vendors_list.OutputParameters insertCARVENDORSLIST(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/insert_car_vendors_list/", partName = "body")
        com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.insert_car_vendors_list.InputParameters body);

    /**
     * 
     * @param header
     * @param body
     * @return
     *     returns com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.update_car_vendors_list.OutputParameters
     */
    @WebMethod(operationName = "UPDATE_CAR_VENDORS_LIST", action = "http://develop.china-fuhai.net:8005/webservices/SOAProvider/plsql/cux_car_manage_sys_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/update_car_vendors_list/", partName = "body")
    public com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.update_car_vendors_list.OutputParameters updateCARVENDORSLIST(
        @WebParam(name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/", header = true, partName = "header")
        SOAHeader header,
        @WebParam(name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_car_manage_sys_pkg/update_car_vendors_list/", partName = "body")
        com.oracle.xmlns.apps.cux.soaprovider.plsql.cux_car_manage_sys_pkg.update_car_vendors_list.InputParameters body);

}
