
package com.example.wsdemo.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://service.wsdemo.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @return
     *     returns com.example.wsdemo.service.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://service.wsdemo.example.com/", className = "com.example.wsdemo.service.GetStudent")
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://service.wsdemo.example.com/", className = "com.example.wsdemo.service.GetStudentResponse")
    public Student getStudent();

}
